/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypaint;

import java.awt.Color;
import java.util.List;
import java.util.Stack;
import javax.swing.JColorChooser;

/**
 *
 * @author mas
 */
public class WindowPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WindowPrincipal.class.getName());

    private Form form;
    
    private Stack<Form> undo = new Stack<>();
    private Stack<Form> redo = new Stack<>();
    
    
    /**
     * Creates new form WindowPrincipal
     */
    public WindowPrincipal() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        panelDraw = new mypaint.PanelDraw();
        panelForms = new javax.swing.JPanel();
        btnLine = new javax.swing.JToggleButton();
        btnRectangle = new javax.swing.JToggleButton();
        btnElipse = new javax.swing.JToggleButton();
        panelOutline = new javax.swing.JPanel();
        panelFill = new javax.swing.JPanel();
        btnUndo = new javax.swing.JButton();
        btnRedo = new javax.swing.JButton();
        btnPen = new javax.swing.JToggleButton();
        btnEraser = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("my(precarious)Paint ");

        panelDraw.setPreferredSize(new java.awt.Dimension(600, 400));
        panelDraw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelDrawMouseDragged(evt);
            }
        });
        panelDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelDrawMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelDrawMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panelDrawLayout = new javax.swing.GroupLayout(panelDraw);
        panelDraw.setLayout(panelDrawLayout);
        panelDrawLayout.setHorizontalGroup(
            panelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelDrawLayout.setVerticalGroup(
            panelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        panelForms.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Forms", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        buttonGroup.add(btnLine);
        btnLine.setText("Line");
        btnLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineActionPerformed(evt);
            }
        });

        buttonGroup.add(btnRectangle);
        btnRectangle.setText("Rectangle");
        btnRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectangleActionPerformed(evt);
            }
        });

        buttonGroup.add(btnElipse);
        btnElipse.setText("Elipse");
        btnElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElipseActionPerformed(evt);
            }
        });

        panelOutline.setBackground(new java.awt.Color(0, 0, 0));
        panelOutline.setToolTipText("Outline Color");
        panelOutline.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOutline.setPreferredSize(new java.awt.Dimension(20, 20));
        panelOutline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelOutlineMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelOutlineLayout = new javax.swing.GroupLayout(panelOutline);
        panelOutline.setLayout(panelOutlineLayout);
        panelOutlineLayout.setHorizontalGroup(
            panelOutlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelOutlineLayout.setVerticalGroup(
            panelOutlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelFill.setBackground(new java.awt.Color(100, 100, 100));
        panelFill.setToolTipText("Outline Color");
        panelFill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelFill.setPreferredSize(new java.awt.Dimension(20, 20));
        panelFill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFillMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelFillLayout = new javax.swing.GroupLayout(panelFill);
        panelFill.setLayout(panelFillLayout);
        panelFillLayout.setHorizontalGroup(
            panelFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelFillLayout.setVerticalGroup(
            panelFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        btnUndo.setText("<-");
        buttonGroup.add(btnUndo);
        btnUndo.setPreferredSize(new java.awt.Dimension(70, 28));
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoClicked(evt);
            }
        });

        btnRedo.setText("->");
        buttonGroup.add(btnRedo);
        btnRedo.setPreferredSize(new java.awt.Dimension(70, 28));
        btnRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedoClicked(evt);
            }
        });

        buttonGroup.add(btnPen);
        btnPen.setText("Pen");
        btnPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenActionPerformed(evt);
            }
        });

        buttonGroup.add(btnEraser);
        btnEraser.setText("Eraser");
        btnEraser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEraserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormsLayout = new javax.swing.GroupLayout(panelForms);
        panelForms.setLayout(panelFormsLayout);
        panelFormsLayout.setHorizontalGroup(
            panelFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelFormsLayout.createSequentialGroup()
                        .addComponent(btnLine, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormsLayout.createSequentialGroup()
                        .addComponent(btnRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnElipse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnEraser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(panelFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormsLayout.createSequentialGroup()
                        .addComponent(panelFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelOutline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormsLayout.createSequentialGroup()
                        .addComponent(btnUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRedo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFormsLayout.setVerticalGroup(
            panelFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormsLayout.createSequentialGroup()
                .addGroup(panelFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormsLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnEraser))
                    .addGroup(panelFormsLayout.createSequentialGroup()
                        .addGroup(panelFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRedo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelOutline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelFill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFormsLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(panelFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLine)
                            .addComponent(btnPen))
                        .addGap(10, 10, 10)
                        .addGroup(panelFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRectangle)
                            .addComponent(btnElipse))))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelForms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelDraw, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelForms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelForms.getAccessibleContext().setAccessibleName("Palette");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelDrawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawMousePressed
          
        
        if( btnLine.isSelected() ) {
            form = new Line();
        } else if( btnRectangle.isSelected() ) {
            form = new Rectangle();
        } else if ( btnElipse.isSelected() ) {
            form = new Elipse();
        } else if ( btnPen.isSelected() ) {
            form = new Pen();
            form.setX1(evt.getX());
            form.setY1(evt.getY());
            form.setOutline(panelOutline.getBackground());
            panelDraw.addForm(form); 
            panelDraw.repaint();+
            return; 
        } else if ( btnEraser.isSelected() ) {
            form = new Eraser();
            form.setX1(evt.getX());
            form.setY1(evt.getY());
            panelDraw.addForm(form);
            panelDraw.repaint();
            return; 
        }

        form.setX1( evt.getX() );
        form.setY1( evt.getY() );
        form.setOutline( panelOutline.getBackground() );
        form.setFill( panelFill.getBackground() );
        
    }//GEN-LAST:event_panelDrawMousePressed

    private void panelDrawMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawMouseReleased
        
       if ( btnPen.isSelected() || btnEraser.isSelected() ) {
            return;
        }
    
        form.setX2( evt.getX() );
        form.setY2( evt.getY() );

        panelDraw.addForm( form );
        panelDraw.setFormTemp( null );

        panelDraw.repaint();
    }//GEN-LAST:event_panelDrawMouseReleased

    private void panelDrawMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawMouseDragged
        
       if ( btnPen.isSelected() ) {
        Form newPen = new Pen();
        newPen.setX1(evt.getX());
        newPen.setY1(evt.getY());
        newPen.setOutline(panelOutline.getBackground());
        panelDraw.addForm(newPen);
        panelDraw.repaint();
        
    } else if ( btnEraser.isSelected() ) {
        Form newEraser = new Eraser();
        newEraser.setX1(evt.getX());
        newEraser.setY1(evt.getY());
        panelDraw.addForm(newEraser);
        panelDraw.repaint();
        
    } else {
        form.setX2( evt.getX() );
        form.setY2( evt.getY() );
        
        panelDraw.setFormTemp( form );
        panelDraw.repaint();
    }
        
    }//GEN-LAST:event_panelDrawMouseDragged

    private void btnLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLineActionPerformed

    private void btnElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElipseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnElipseActionPerformed

    private void btnRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectangleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRectangleActionPerformed

    private void panelOutlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOutlineMouseClicked
        
        Color c = JColorChooser.showDialog(
                this,
                "Outline Color",
                panelOutline.getBackground() );
        
        if( c != null ) {
            panelOutline.setBackground( c );
        }
        
    }//GEN-LAST:event_panelOutlineMouseClicked

    private void panelFillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFillMouseClicked
        
        Color c = JColorChooser.showDialog(
                this,
                "Fill Color",
                panelFill.getBackground() );
        
        if( c != null ) {
            panelFill.setBackground( c );
        }
        
    }//GEN-LAST:event_panelFillMouseClicked

    private void btnPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPenActionPerformed

    private void btnEraserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEraserActionPerformed

    private void btnUndoClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoClicked
        
        if ( !panelDraw.getForms().isEmpty() ) {
            List<Form> currentForms = panelDraw.getForms();
            Form lastForm = currentForms.remove(currentForms.size() - 1);
            redo.push(lastForm);

            panelDraw.setForms( currentForms );
            panelDraw.repaint();
        }
    }//GEN-LAST:event_btnUndoClicked

    private void btnRedoClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedoClicked
        
        if ( !redo.isEmpty() ) {
            Form formToRestore = redo.pop();
            List<Form> currentForms = panelDraw.getForms();
            currentForms.add(formToRestore);

            panelDraw.setForms( currentForms );
            panelDraw.repaint();
        }
    }//GEN-LAST:event_btnRedoClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnElipse;
    private javax.swing.JToggleButton btnEraser;
    private javax.swing.JToggleButton btnLine;
    private javax.swing.JToggleButton btnPen;
    private javax.swing.JToggleButton btnRectangle;
    private javax.swing.JButton btnRedo;
    private javax.swing.JButton btnUndo;
    private javax.swing.ButtonGroup buttonGroup;
    private mypaint.PanelDraw panelDraw;
    private javax.swing.JPanel panelFill;
    private javax.swing.JPanel panelForms;
    private javax.swing.JPanel panelOutline;
    // End of variables declaration//GEN-END:variables
}
